name: Build app bundle

on:
  release:
    types: [created]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1

jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Use XCode 26.0
        run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app

      - name: Install dotnet workload to compile for macOS
        run: dotnet workload install macos

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish app bundle
        run: dotnet publish --configuration Release --no-restore -p:AssemblyVersion=${{ github.ref_name }} -o publish/ src/AppBlock

      - name: Upload bundle to release
        uses: softprops/action-gh-release@2bc819c87a4e63a4ac4e581a02085318bd49975a
        with:
          files: |
            publish/AppBlock-${{ github.ref_name }}.zip
            publish/AppBlock-${{ github.ref_name }}.zip-CHECKSUM

      - name: Show checksum for release
        run: cat publish/AppBlock-${{ github.ref_name }}.zip-CHECKSUM
